In [1]:
import numpy as np

In [2]:
a = np.array([[1, 6], [2, 8], [3, 11], [3, 10], [1, 7]], int)
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [7]:
mean_a = a.mean(axis = 0)
mean_a

array([2. , 8.4])

In [8]:
a_centered = a - mean_a
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

In [9]:
a_centered_sp = np.dot(a_centered[:, 0], a_centered[:, 1])
a_centered_sp

8.0

In [11]:
a_centered_sp / (len(a_centered) - 1)

2.0

In [12]:
cov = np.cov(a.T)
cov

array([[1. , 2. ],
       [2. , 4.3]])

 Первый элемент нулевой строки равен 2. Значит первый варинт посчитан верно.